config/routes.rb
Rails.application.routes.draw do
  resources :purchases do
    member do
      post :capture
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "purchases#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  # GET /purchases or /purchases.json
  def index
    @purchases = FatZebra::Purchase.search.data
  end

  # GET /purchases/1 or /purchases/1.json
  def show
    @purchase = FatZebra::Purchase.find(params[:id])
  end

  # POST /purchases or /purchases.json
  def create

  end

  # PATCH/PUT /purchases/1 or /purchases/1.json
  def update

  end

  # DELETE /purchases/1 or /purchases/1.json
  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
  def success_tag(text)
    zeal_tag(text, additional_classes: "bg-success-100 text-success-800")
  end

  def flag_tag(text)
    zeal_tag(text, additional_classes: "bg-flag-100 text-flag-800")
  end

  def zeal_tag(text, additional_classes: )
    tag.span(class: "inline-flex items-center h-8 px-2.5 py-0.5 rounded font-medium text-xs mr-2 " + additional_classes) { text }
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gazelle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800&display=swap" rel="stylesheet">

  </head>

  <body>
    <div class="p-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render "form", purchase: @purchase %>

<br>

<div>
  <%= link_to "Show this purchase", @purchase %> |
  <%= link_to "Back to purchases", purchases_path %>
</div>

app/views/purchases/index.html.erb
<p style="color: green"><%= notice %></p>

  <h1 class="text-4xl mb-8 mr-2">Purchases</h1>
  <div class="mb-4">
    <%= link_to "New authorization", new_purchase_path, class: "py-2 px-4 h-10 inline-flex items-center rounded-lg whitespace-nowrap disabled:cursor-not-allowed text-sm active:bg-primary-600 bg-primary-500 text-white disabled:bg-primary-300 mr-2" %>
  </div>

<div class="relative overflow-x-auto sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50">
      <tr>
        <th scope="col" class="px-6 py-3">
          Status
        </th>
        <th scope="col" class="px-6 py-3">
          Purchase ID
        </th>
        <th scope="col" class="px-6 py-3">
          Timestamp
        </th>
        <th scope="col" class="px-6 py-3">
          Amount
        </th>
        <th scope="col" class="px-6 py-3">
          Customer
        </th>
      </tr>

    </thead>
    <tbody>
      <% @purchases.each do |purchase| %>
        <tr class="bg-white border-b">
          <td class="px-6 py-3">
            <%= purchase.captured? ? success_tag("Captured") : flag_tag("Authorized") %><br />
          </td>
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">
              <%= link_to purchase.id, purchase_path(purchase.id) %>
          </th>
          <td class="px-6 py-3">
            <%= time_ago_in_words(purchase.transaction_date) %> ago
          </td>
          <td class="px-6 py-3">
            <%= Money.new(purchase.amount, purchase.currency).format(with_currency: true) %>
          </td>
          <td class="px-6 py-3">
            <%= purchase.card_holder %><br />
            <%= purchase.card_number.gsub(/X+/, '···').html_safe %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/purchases/new.html.erb
<div class="flex py-8 flex-1">
  <div class='my-10 max-w-[700px] w-full md:px-0 md:w-3/4 lg:w-3/5 mx-auto'>
    <h1>New Authorization</h1>
    <%= form_with(url: purchases_path, builder: ZealFormBuilder, scope: :purchase) do |form| %>
      <div class="mb-4">
        <%= form.label :amount %>
        <%= form.text_field :amount %>
      </div>

      <div class="mb-4">
        <%= form.label :card_holder %>
        <%= form.text_field :card_holder %>
      </div>

      <div class="mb-4">
        <%= form.label :card_number %>
        <%= form.text_field :card_number %>
      </div>

      <div class="mb-4 grid grid-cols-2 gap-2">
        <div>
          <%= form.label :cvv, "CVV" %>
          <%= form.text_field :cvv %>
        </div>
        <div>
          <%= form.label :card_expiry %>
          <%= form.text_field :card_expiry %>
        </div>
      </div>

      <div class="mb-4">
        <%= form.label :reference %>
        <%= form.text_field :reference %>
      </div>

      <div>
        <%= form.submit "Authorize Purchase", class: "py-2 px-4 h-10 inline-flex items-center rounded-lg whitespace-nowrap disabled:cursor-not-allowed text-sm active:bg-primary-600 bg-primary-500 text-white disabled:bg-primary-300 mr-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/purchases/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <div class="flex items-center">
    <h1 class="text-4xl my-0 mr-2"><%= Money.new(@purchase.amount, @purchase.currency).format(with_currency: true) %></h1>
    <%= @purchase.captured? ? success_tag("Captured") : flag_tag("Authorized") %><br />
  </div>

  <p>
    <strong>ID</strong>
    <%= @purchase.id %>
  </p>

     <div>
      <%= button_to "Capture Purchase", capture_purchase_path, class: "py-2 px-4 h-10 inline-flex items-center rounded-lg whitespace-nowrap disabled:cursor-not-allowed text-sm active:bg-primary-600 bg-primary-500 text-white disabled:bg-primary-300 mr-2", method: :post %>
    </div>

</div>